# Generated by Django 5.1.3 on 2024-12-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('background', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('martialStyle', models.CharField(max_length=255)),
                ('body', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('mind', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('resistance', models.IntegerField(default=0)),
                ('deadlift', models.IntegerField(default=0)),
                ('dodge', models.IntegerField(default=0)),
                ('actions', models.IntegerField(default=0)),
                ('deadeye', models.IntegerField(default=0)),
                ('critical_reduction', models.IntegerField(default=0)),
                ('willpower', models.IntegerField(default=0)),
                ('skillpoints', models.IntegerField(default=0)),
                ('skillcap', models.IntegerField(default=0)),
                ('skillnumber', models.IntegerField(default=0)),
                ('skillsadded', models.JSONField(default=list, null=True)),
                ('level', models.IntegerField(default=0)),
                ('actives', models.JSONField(default=list, null=True)),
                ('joblevel', models.IntegerField(default=0)),
                ('jobtoken', models.IntegerField(default=0)),
                ('jobtalents', models.JSONField(default=list, null=True)),
                ('jobskills', models.JSONField(default=list, null=True)),
                ('martialStylelevel', models.IntegerField(default=0)),
                ('martialStyletoken', models.IntegerField(default=0)),
                ('martialStyletalents', models.JSONField(default=list, null=True)),
                ('backgroundskills', models.JSONField(default=list, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
