# Generated by Django 5.1.3 on 2024-12-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='martialStyle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
