# Generated by Django 5.1.3 on 2024-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_character_actives_alter_character_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
